version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: lekhaly_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lekhaly_accounting
    ports:
      - "5432:5432"
    volumes:
      - lekhaly_pg:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: lekhaly_redis
    ports:
      - "6379:6379"

volumes:
  lekhaly_pg:
